--------------------------------------------------------
--  파일이 생성됨 - 월요일-10월-07-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "REDBULL"."BOARD" 
   (	"BNUM" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TITLE" VARCHAR2(100 CHAR), 
	"CONTENTS" CLOB, 
	"READCNT" NUMBER(7,0) DEFAULT 0, 
	"TNUM" NUMBER(3,0), 
	"CATEGORY" VARCHAR2(10 CHAR), 
	"REGID" VARCHAR2(320 CHAR), 
	"REGDT" DATE, 
	"MODID" VARCHAR2(320 CHAR), 
	"MODDT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" 
 LOB ("CONTENTS") STORE AS SECUREFILE (
  TABLESPACE "REDBULL_TS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "REDBULL"."BOARD"."BNUM" IS '질문번호';
   COMMENT ON COLUMN "REDBULL"."BOARD"."TITLE" IS '제목';
   COMMENT ON COLUMN "REDBULL"."BOARD"."CONTENTS" IS '내용';
   COMMENT ON COLUMN "REDBULL"."BOARD"."READCNT" IS '조회수';
   COMMENT ON COLUMN "REDBULL"."BOARD"."TNUM" IS '테이블번호';
   COMMENT ON COLUMN "REDBULL"."BOARD"."CATEGORY" IS '카테고리';
   COMMENT ON COLUMN "REDBULL"."BOARD"."REGID" IS '등록자';
   COMMENT ON COLUMN "REDBULL"."BOARD"."REGDT" IS '등록일';
   COMMENT ON COLUMN "REDBULL"."BOARD"."MODID" IS '수정자';
   COMMENT ON COLUMN "REDBULL"."BOARD"."MODDT" IS '수정일';
   COMMENT ON TABLE "REDBULL"."BOARD"  IS '게시판';
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "REDBULL"."CART" 
   (	"CARTNUM" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PNUM" NUMBER, 
	"CARTCNT" NUMBER(4,0) DEFAULT 1, 
	"REGID" VARCHAR2(320 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;

   COMMENT ON COLUMN "REDBULL"."CART"."CARTNUM" IS '장바구니번호';
   COMMENT ON COLUMN "REDBULL"."CART"."PNUM" IS '상품번호';
   COMMENT ON COLUMN "REDBULL"."CART"."CARTCNT" IS '수량';
   COMMENT ON COLUMN "REDBULL"."CART"."REGID" IS '등록자';
   COMMENT ON TABLE "REDBULL"."CART"  IS '장바구니';
--------------------------------------------------------
--  DDL for Table CODE
--------------------------------------------------------

  CREATE TABLE "REDBULL"."CODE" 
   (	"CODE_TYPE_ID" VARCHAR2(30 BYTE), 
	"CODE_ID" VARCHAR2(30 BYTE), 
	"CODE_NM" VARCHAR2(100 BYTE), 
	"USE_YN" CHAR(1 BYTE) DEFAULT 0, 
	"NUM" NUMBER, 
	"REG_ID" VARCHAR2(20 BYTE), 
	"REG_DT" DATE, 
	"MOD_ID" VARCHAR2(20 BYTE), 
	"MOD_DT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "REDBULL_TS" ;

   COMMENT ON COLUMN "REDBULL"."CODE"."CODE_TYPE_ID" IS '코드유형ID';
   COMMENT ON COLUMN "REDBULL"."CODE"."CODE_ID" IS '코드ID';
   COMMENT ON COLUMN "REDBULL"."CODE"."CODE_NM" IS '코드명';
   COMMENT ON COLUMN "REDBULL"."CODE"."USE_YN" IS '사용여부';
   COMMENT ON COLUMN "REDBULL"."CODE"."NUM" IS '순서';
   COMMENT ON COLUMN "REDBULL"."CODE"."REG_ID" IS '등록자ID';
   COMMENT ON COLUMN "REDBULL"."CODE"."REG_DT" IS '등록일';
   COMMENT ON COLUMN "REDBULL"."CODE"."MOD_ID" IS '수정자ID';
   COMMENT ON COLUMN "REDBULL"."CODE"."MOD_DT" IS '수정일';
   COMMENT ON TABLE "REDBULL"."CODE"  IS '공통코드';
--------------------------------------------------------
--  DDL for Table CODE_TYPE
--------------------------------------------------------

  CREATE TABLE "REDBULL"."CODE_TYPE" 
   (	"CODE_TYPE_ID" VARCHAR2(30 BYTE), 
	"CODE_TYPE_NM" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "REDBULL_TS" ;

   COMMENT ON COLUMN "REDBULL"."CODE_TYPE"."CODE_TYPE_ID" IS '코드유형ID';
   COMMENT ON COLUMN "REDBULL"."CODE_TYPE"."CODE_TYPE_NM" IS '코드유형명';
   COMMENT ON TABLE "REDBULL"."CODE_TYPE"  IS '공통코드유형';
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "REDBULL"."COMMENTS" 
   (	"CNUM" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TNUM" NUMBER(3,0), 
	"REFNUM" NUMBER, 
	"CONTENTS" CLOB, 
	"HCNUM" NUMBER DEFAULT 0, 
	"REGID" VARCHAR2(320 CHAR), 
	"REGDT" DATE, 
	"MODID" VARCHAR2(320 CHAR), 
	"MODDT" DATE, 
	"CLEVEL" NUMBER(2,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" 
 LOB ("CONTENTS") STORE AS SECUREFILE (
  TABLESPACE "REDBULL_TS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "REDBULL"."COMMENTS"."CNUM" IS '댓글번호';
   COMMENT ON COLUMN "REDBULL"."COMMENTS"."TNUM" IS '테이블번호';
   COMMENT ON COLUMN "REDBULL"."COMMENTS"."REFNUM" IS '참조번호';
   COMMENT ON COLUMN "REDBULL"."COMMENTS"."CONTENTS" IS '내용';
   COMMENT ON COLUMN "REDBULL"."COMMENTS"."HCNUM" IS '상위댓글번호';
   COMMENT ON COLUMN "REDBULL"."COMMENTS"."REGID" IS '등록자';
   COMMENT ON COLUMN "REDBULL"."COMMENTS"."REGDT" IS '등록일';
   COMMENT ON COLUMN "REDBULL"."COMMENTS"."MODID" IS '수정자';
   COMMENT ON COLUMN "REDBULL"."COMMENTS"."MODDT" IS '수정일';
   COMMENT ON TABLE "REDBULL"."COMMENTS"  IS '댓글';
--------------------------------------------------------
--  DDL for Table GOOD
--------------------------------------------------------

  CREATE TABLE "REDBULL"."GOOD" 
   (	"GNUM" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PNUM" NUMBER, 
	"REGID" VARCHAR2(320 CHAR), 
	"REGDT" DATE, 
	"LINK" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;

   COMMENT ON COLUMN "REDBULL"."GOOD"."GNUM" IS '좋아요번호';
   COMMENT ON COLUMN "REDBULL"."GOOD"."PNUM" IS '상품번호';
   COMMENT ON COLUMN "REDBULL"."GOOD"."REGID" IS '등록자';
   COMMENT ON COLUMN "REDBULL"."GOOD"."REGDT" IS '등록일';
   COMMENT ON COLUMN "REDBULL"."GOOD"."LINK" IS '링크';
   COMMENT ON TABLE "REDBULL"."GOOD"  IS '좋아요';
--------------------------------------------------------
--  DDL for Table IMAGE
--------------------------------------------------------

  CREATE TABLE "REDBULL"."IMAGE" 
   (	"INUM" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"REFNUM" NUMBER, 
	"ORG_FILE_NM" VARCHAR2(255 CHAR), 
	"SAVE_FILE_NM" VARCHAR2(255 CHAR), 
	"FILE_SIZE" VARCHAR2(7 BYTE), 
	"EXT_NM" VARCHAR2(4 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;

   COMMENT ON COLUMN "REDBULL"."IMAGE"."INUM" IS '이미지번호';
   COMMENT ON COLUMN "REDBULL"."IMAGE"."REFNUM" IS '참조번호';
   COMMENT ON COLUMN "REDBULL"."IMAGE"."ORG_FILE_NM" IS '원본파일명';
   COMMENT ON COLUMN "REDBULL"."IMAGE"."SAVE_FILE_NM" IS '저장파일명';
   COMMENT ON COLUMN "REDBULL"."IMAGE"."FILE_SIZE" IS '사이즈';
   COMMENT ON COLUMN "REDBULL"."IMAGE"."EXT_NM" IS '확장자';
   COMMENT ON TABLE "REDBULL"."IMAGE"  IS '이미지';
--------------------------------------------------------
--  DDL for Table OPT
--------------------------------------------------------

  CREATE TABLE "REDBULL"."OPT" 
   (	"ONUM" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ONAME" VARCHAR2(100 CHAR), 
	"OPRICE" NUMBER(7,0), 
	"PNUM" NUMBER, 
	"INUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;

   COMMENT ON COLUMN "REDBULL"."OPT"."ONUM" IS '옵션번호';
   COMMENT ON COLUMN "REDBULL"."OPT"."ONAME" IS '옵션명';
   COMMENT ON COLUMN "REDBULL"."OPT"."OPRICE" IS '가격';
   COMMENT ON COLUMN "REDBULL"."OPT"."PNUM" IS '상품번호';
   COMMENT ON COLUMN "REDBULL"."OPT"."INUM" IS '이미지번호';
   COMMENT ON TABLE "REDBULL"."OPT"  IS '옵션';
--------------------------------------------------------
--  DDL for Table PAY
--------------------------------------------------------

  CREATE TABLE "REDBULL"."PAY" 
   (	"PAYNUM" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ORDERNUM" NUMBER, 
	"ONUM" NUMBER, 
	"PAYCNT" NUMBER(4,0) DEFAULT 1, 
	"DNAME" VARCHAR2(17 CHAR), 
	"DPOSTNUM" NUMBER(5,0), 
	"DAAD" VARCHAR2(30 CHAR), 
	"DDETADD" VARCHAR2(100 CHAR), 
	"DPHONE" VARCHAR2(13 BYTE), 
	"DMEMO" VARCHAR2(100 CHAR), 
	"PAYID" VARCHAR2(320 CHAR), 
	"PAYDT" DATE, 
	"INUM" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "REDBULL_TS" ;

   COMMENT ON COLUMN "REDBULL"."PAY"."PAYNUM" IS '결제번호';
   COMMENT ON COLUMN "REDBULL"."PAY"."ORDERNUM" IS '주문번호';
   COMMENT ON COLUMN "REDBULL"."PAY"."ONUM" IS '옵션번호';
   COMMENT ON COLUMN "REDBULL"."PAY"."PAYCNT" IS '결제수량';
   COMMENT ON COLUMN "REDBULL"."PAY"."DNAME" IS '배송받는사람';
   COMMENT ON COLUMN "REDBULL"."PAY"."DPOSTNUM" IS '배송우편번호';
   COMMENT ON COLUMN "REDBULL"."PAY"."DAAD" IS '배송주소';
   COMMENT ON COLUMN "REDBULL"."PAY"."DDETADD" IS '배송자세한주소';
   COMMENT ON COLUMN "REDBULL"."PAY"."DPHONE" IS '배송휴대폰번호';
   COMMENT ON COLUMN "REDBULL"."PAY"."DMEMO" IS '배송메모';
   COMMENT ON COLUMN "REDBULL"."PAY"."PAYID" IS '결제자';
   COMMENT ON COLUMN "REDBULL"."PAY"."PAYDT" IS '결제일';
   COMMENT ON COLUMN "REDBULL"."PAY"."INUM" IS '이미지번호';
   COMMENT ON TABLE "REDBULL"."PAY"  IS '결제';
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "REDBULL"."PRODUCT" 
   (	"PNUM" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PNAME" VARCHAR2(100 CHAR), 
	"BPRICE" NUMBER(7,0), 
	"DETAIL" CLOB, 
	"DISCOUNT" NUMBER(3,2) DEFAULT 0, 
	"DPRICE" NUMBER(5,0) DEFAULT 0, 
	"PCATEGORY" NUMBER(3,0) DEFAULT 10, 
	"REGID" VARCHAR2(320 CHAR), 
	"REGDT" DATE, 
	"MODID" VARCHAR2(320 CHAR), 
	"MODDT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" 
 LOB ("DETAIL") STORE AS SECUREFILE (
  TABLESPACE "REDBULL_TS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "REDBULL"."PRODUCT"."PNUM" IS '상품번호';
   COMMENT ON COLUMN "REDBULL"."PRODUCT"."PNAME" IS '상품명';
   COMMENT ON COLUMN "REDBULL"."PRODUCT"."BPRICE" IS '기본가격';
   COMMENT ON COLUMN "REDBULL"."PRODUCT"."DETAIL" IS '상세정보';
   COMMENT ON COLUMN "REDBULL"."PRODUCT"."DISCOUNT" IS '할인율';
   COMMENT ON COLUMN "REDBULL"."PRODUCT"."DPRICE" IS '배송비';
   COMMENT ON COLUMN "REDBULL"."PRODUCT"."PCATEGORY" IS '카테고리';
   COMMENT ON COLUMN "REDBULL"."PRODUCT"."REGID" IS '등록자';
   COMMENT ON COLUMN "REDBULL"."PRODUCT"."REGDT" IS '등록일';
   COMMENT ON COLUMN "REDBULL"."PRODUCT"."MODID" IS '수정자';
   COMMENT ON COLUMN "REDBULL"."PRODUCT"."MODDT" IS '수정일';
   COMMENT ON TABLE "REDBULL"."PRODUCT"  IS '상품';
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE "REDBULL"."REVIEW" 
   (	"RNUM" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PNUM" NUMBER, 
	"SCORE" NUMBER(2,1) DEFAULT 0, 
	"CONTENTS" CLOB, 
	"REGID" VARCHAR2(320 CHAR), 
	"REGDT" DATE, 
	"MODID" VARCHAR2(320 CHAR), 
	"MODDT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" 
 LOB ("CONTENTS") STORE AS SECUREFILE (
  TABLESPACE "REDBULL_TS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "REDBULL"."REVIEW"."RNUM" IS '리뷰번호';
   COMMENT ON COLUMN "REDBULL"."REVIEW"."PNUM" IS '상품번호';
   COMMENT ON COLUMN "REDBULL"."REVIEW"."SCORE" IS '별점';
   COMMENT ON COLUMN "REDBULL"."REVIEW"."CONTENTS" IS '내용';
   COMMENT ON COLUMN "REDBULL"."REVIEW"."REGID" IS '등록자';
   COMMENT ON COLUMN "REDBULL"."REVIEW"."REGDT" IS '등록일';
   COMMENT ON COLUMN "REDBULL"."REVIEW"."MODID" IS '수정자';
   COMMENT ON COLUMN "REDBULL"."REVIEW"."MODDT" IS '수정일';
   COMMENT ON TABLE "REDBULL"."REVIEW"  IS '리뷰';
--------------------------------------------------------
--  DDL for Table RUSER
--------------------------------------------------------

  CREATE TABLE "REDBULL"."RUSER" 
   (	"RID" VARCHAR2(320 CHAR), 
	"PASSWD" VARCHAR2(20 BYTE), 
	"UNAME" VARCHAR2(17 CHAR), 
	"BIRTH" VARCHAR2(10 BYTE), 
	"PHONE" VARCHAR2(13 BYTE), 
	"POSTNUM" NUMBER(5,0), 
	"ADDRESS" VARCHAR2(30 BYTE), 
	"DETADD" VARCHAR2(100 CHAR), 
	"LVL" NUMBER(3,0) DEFAULT 10, 
	"UPOINT" NUMBER(6,0) DEFAULT 0, 
	"INUM" NUMBER, 
	"REGDT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;

   COMMENT ON COLUMN "REDBULL"."RUSER"."RID" IS '아이디';
   COMMENT ON COLUMN "REDBULL"."RUSER"."PASSWD" IS '비밀번호';
   COMMENT ON COLUMN "REDBULL"."RUSER"."UNAME" IS '이름';
   COMMENT ON COLUMN "REDBULL"."RUSER"."BIRTH" IS '생년월일';
   COMMENT ON COLUMN "REDBULL"."RUSER"."PHONE" IS '휴대폰번호';
   COMMENT ON COLUMN "REDBULL"."RUSER"."POSTNUM" IS '우편번호';
   COMMENT ON COLUMN "REDBULL"."RUSER"."ADDRESS" IS '주소';
   COMMENT ON COLUMN "REDBULL"."RUSER"."DETADD" IS '자세한주소';
   COMMENT ON COLUMN "REDBULL"."RUSER"."LVL" IS '레벨';
   COMMENT ON COLUMN "REDBULL"."RUSER"."UPOINT" IS '포인트';
   COMMENT ON COLUMN "REDBULL"."RUSER"."INUM" IS '이미지번호';
   COMMENT ON COLUMN "REDBULL"."RUSER"."REGDT" IS '등록일';
   COMMENT ON TABLE "REDBULL"."RUSER"  IS '회원';
REM INSERTING into REDBULL.BOARD
SET DEFINE OFF;
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (242,'우왕',0,20,'질답카테고리02',null,to_date('19/09/27','RR/MM/DD'),null,to_date('19/09/27','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (261,'테스트1',0,20,'질답카테고리02',null,to_date('19/09/30','RR/MM/DD'),null,to_date('19/09/30','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (262,'우왕',0,20,'질답카테고리03',null,to_date('19/09/30','RR/MM/DD'),null,to_date('19/09/30','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (263,'ㅇㅇㅇㅇ',0,20,'질답카테고리02',null,to_date('19/09/30','RR/MM/DD'),null,to_date('19/09/30','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (265,'1111111',0,10,'공지',null,to_date('19/09/30','RR/MM/DD'),null,to_date('19/09/30','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (234,'test',0,10,'1',null,to_date('19/09/26','RR/MM/DD'),null,to_date('19/09/26','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (236,'4343455',0,20,'질답카테고리01',null,to_date('19/09/26','RR/MM/DD'),null,to_date('19/09/26','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (237,'1111',0,20,'질답카테고리04',null,to_date('19/09/26','RR/MM/DD'),null,to_date('19/09/26','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (235,'12312312312312313',0,10,'공지',null,to_date('19/09/26','RR/MM/DD'),null,to_date('19/09/26','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (238,'공지테스트',0,10,'공지',null,to_date('19/09/26','RR/MM/DD'),null,to_date('19/09/26','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (244,'테스트글쓰기',0,20,'질답카테고리02',null,to_date('19/09/27','RR/MM/DD'),null,to_date('19/09/27','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (243,'수정',0,20,'질답카테고리01',null,to_date('19/09/27','RR/MM/DD'),null,to_date('19/09/27','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (245,'공지테스트',0,10,'공지',null,to_date('19/09/27','RR/MM/DD'),null,to_date('19/09/27','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (246,'공지1',0,10,'공지',null,to_date('19/09/27','RR/MM/DD'),null,to_date('19/09/27','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (247,'공지공지공지',0,10,'공지',null,to_date('19/09/27','RR/MM/DD'),null,to_date('19/09/27','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (248,'111111',0,20,'질답카테고리03',null,to_date('19/09/27','RR/MM/DD'),null,to_date('19/09/27','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (249,'123131231',0,20,'질답카테고리04',null,to_date('19/09/27','RR/MM/DD'),null,to_date('19/09/27','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (250,'123121111111',0,20,'질답카테고리04',null,to_date('19/09/27','RR/MM/DD'),null,to_date('19/09/27','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (264,'우왕',0,20,'질답카테고리01',null,to_date('19/09/30','RR/MM/DD'),null,to_date('19/09/30','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (204,'update',0,10,'update','admin',to_date('19/09/25','RR/MM/DD'),'update',to_date('19/09/25','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (281,'제목01',0,1,'카테고리01','admin',to_date('19/10/02','RR/MM/DD'),'admin',to_date('19/10/02','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (282,'제목02',0,1,'카테고리02','admin',to_date('19/10/02','RR/MM/DD'),'admin',to_date('19/10/02','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (283,'제목03',0,1,'카테고리03','admin',to_date('19/10/02','RR/MM/DD'),'admin',to_date('19/10/02','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (284,'제목04',0,1,'카테고리04','admin',to_date('19/10/02','RR/MM/DD'),'admin',to_date('19/10/02','RR/MM/DD'));
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT) values (285,'제목05',0,1,'카테고리05','admin',to_date('19/10/02','RR/MM/DD'),'admin',to_date('19/10/02','RR/MM/DD'));
REM INSERTING into REDBULL.CART
SET DEFINE OFF;
Insert into REDBULL.CART (CARTNUM,PNUM,CARTCNT,REGID) values (24,71,1,'J07');
Insert into REDBULL.CART (CARTNUM,PNUM,CARTCNT,REGID) values (26,73,1,'J09');
Insert into REDBULL.CART (CARTNUM,PNUM,CARTCNT,REGID) values (27,75,1,'J07');
Insert into REDBULL.CART (CARTNUM,PNUM,CARTCNT,REGID) values (29,73,1,'J09');
Insert into REDBULL.CART (CARTNUM,PNUM,CARTCNT,REGID) values (30,111,1,'J07');
Insert into REDBULL.CART (CARTNUM,PNUM,CARTCNT,REGID) values (31,121,1,'J07');
Insert into REDBULL.CART (CARTNUM,PNUM,CARTCNT,REGID) values (33,186,1,'J09');
Insert into REDBULL.CART (CARTNUM,PNUM,CARTCNT,REGID) values (21,7,1,'J07');
Insert into REDBULL.CART (CARTNUM,PNUM,CARTCNT,REGID) values (107,366,2,'cart_130');
Insert into REDBULL.CART (CARTNUM,PNUM,CARTCNT,REGID) values (23,9,1,'J09');
Insert into REDBULL.CART (CARTNUM,PNUM,CARTCNT,REGID) values (87,188,1,'J01등록자_127');
Insert into REDBULL.CART (CARTNUM,PNUM,CARTCNT,REGID) values (105,336,1,'J01등록자_125');
REM INSERTING into REDBULL.CODE
SET DEFINE OFF;
REM INSERTING into REDBULL.CODE_TYPE
SET DEFINE OFF;
REM INSERTING into REDBULL.COMMENTS
SET DEFINE OFF;
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (159,20,264,0,'admin',to_date('19/10/02','RR/MM/DD'),'admin',to_date('19/10/02','RR/MM/DD'),1);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (160,20,264,0,'admin',to_date('19/10/02','RR/MM/DD'),'admin',to_date('19/10/02','RR/MM/DD'),1);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (161,20,264,159,'admin',to_date('19/10/02','RR/MM/DD'),'admin',to_date('19/10/02','RR/MM/DD'),2);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (162,20,264,160,'admin',to_date('19/10/02','RR/MM/DD'),'admin',to_date('19/10/02','RR/MM/DD'),2);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (163,20,264,162,'admin',to_date('19/10/02','RR/MM/DD'),'admin',to_date('19/10/02','RR/MM/DD'),3);
REM INSERTING into REDBULL.GOOD
SET DEFINE OFF;
Insert into REDBULL.GOOD (GNUM,PNUM,REGID,REGDT,LINK) values (1,186,null,null,null);
Insert into REDBULL.GOOD (GNUM,PNUM,REGID,REGDT,LINK) values (2,186,null,null,null);
Insert into REDBULL.GOOD (GNUM,PNUM,REGID,REGDT,LINK) values (3,187,null,null,null);
Insert into REDBULL.GOOD (GNUM,PNUM,REGID,REGDT,LINK) values (4,186,null,null,null);
Insert into REDBULL.GOOD (GNUM,PNUM,REGID,REGDT,LINK) values (5,188,null,null,null);
REM INSERTING into REDBULL.IMAGE
SET DEFINE OFF;
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM) values (47,366,'orgFileNm6','cartFileNm6','6','ext');
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM) values (42,56,'orgFileNm1','saveFileNm1','1','ext');
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM) values (43,57,'orgFileNm2','saveFileNm2','2','ext');
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM) values (44,58,'orgFileNm3','saveFileNm3','3','ext');
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM) values (45,59,'orgFileNm4','saveFileNm4','4','ext');
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM) values (46,60,'orgFileNm5','saveFileNm5','5','ext');
REM INSERTING into REDBULL.OPT
SET DEFINE OFF;
Insert into REDBULL.OPT (ONUM,ONAME,OPRICE,PNUM,INUM) values (36,'J01옵션명_125',10000,71,10);
Insert into REDBULL.OPT (ONUM,ONAME,OPRICE,PNUM,INUM) values (37,'J02옵션명_125',20000,72,10);
Insert into REDBULL.OPT (ONUM,ONAME,OPRICE,PNUM,INUM) values (38,'J03옵션명_125',30000,73,20);
Insert into REDBULL.OPT (ONUM,ONAME,OPRICE,PNUM,INUM) values (39,'J04옵션명_125',40000,74,30);
Insert into REDBULL.OPT (ONUM,ONAME,OPRICE,PNUM,INUM) values (40,'J05옵션명_125',50000,75,30);
REM INSERTING into REDBULL.PAY
SET DEFINE OFF;
REM INSERTING into REDBULL.PRODUCT
SET DEFINE OFF;
Insert into REDBULL.PRODUCT (PNUM,PNAME,BPRICE,DISCOUNT,DPRICE,PCATEGORY,REGID,REGDT,MODID,MODDT) values (366,'J01상품명_125',10000,0.1,1000,10,'J01등록자_125',to_date('19/10/02','RR/MM/DD'),null,null);
Insert into REDBULL.PRODUCT (PNUM,PNAME,BPRICE,DISCOUNT,DPRICE,PCATEGORY,REGID,REGDT,MODID,MODDT) values (367,'J02상품명_125',20000,0.2,2000,10,'J01등록자_125',to_date('19/10/02','RR/MM/DD'),null,null);
Insert into REDBULL.PRODUCT (PNUM,PNAME,BPRICE,DISCOUNT,DPRICE,PCATEGORY,REGID,REGDT,MODID,MODDT) values (368,'J03상품명_125',30000,0.3,3000,20,'J01등록자_125',to_date('19/10/02','RR/MM/DD'),null,null);
Insert into REDBULL.PRODUCT (PNUM,PNAME,BPRICE,DISCOUNT,DPRICE,PCATEGORY,REGID,REGDT,MODID,MODDT) values (369,'J04상품명_125',40000,0.4,4000,30,'J01등록자_125',to_date('19/10/02','RR/MM/DD'),null,null);
Insert into REDBULL.PRODUCT (PNUM,PNAME,BPRICE,DISCOUNT,DPRICE,PCATEGORY,REGID,REGDT,MODID,MODDT) values (370,'J05상품명_125',50000,0.5,5000,30,'J01등록자_125',to_date('19/10/02','RR/MM/DD'),null,null);
REM INSERTING into REDBULL.REVIEW
SET DEFINE OFF;
Insert into REDBULL.REVIEW (RNUM,PNUM,SCORE,REGID,REGDT,MODID,MODDT) values (61,71,1,'noUser',to_date('19/10/02','RR/MM/DD'),null,null);
Insert into REDBULL.REVIEW (RNUM,PNUM,SCORE,REGID,REGDT,MODID,MODDT) values (62,72,2,'noUser',to_date('19/10/02','RR/MM/DD'),null,null);
Insert into REDBULL.REVIEW (RNUM,PNUM,SCORE,REGID,REGDT,MODID,MODDT) values (63,73,3,'noUser',to_date('19/10/02','RR/MM/DD'),null,null);
Insert into REDBULL.REVIEW (RNUM,PNUM,SCORE,REGID,REGDT,MODID,MODDT) values (64,74,4,'noUser',to_date('19/10/02','RR/MM/DD'),null,null);
Insert into REDBULL.REVIEW (RNUM,PNUM,SCORE,REGID,REGDT,MODID,MODDT) values (65,75,5,'noUser',to_date('19/10/02','RR/MM/DD'),null,null);
REM INSERTING into REDBULL.RUSER
SET DEFINE OFF;
Insert into REDBULL.RUSER (RID,PASSWD,UNAME,BIRTH,PHONE,POSTNUM,ADDRESS,DETADD,LVL,UPOINT,INUM,REGDT) values ('rid','passwd','uname','1900-01-01','010-1111-1111',12345,'address','detadd',10,0,0,to_date('19/09/27','RR/MM/DD'));
Insert into REDBULL.RUSER (RID,PASSWD,UNAME,BIRTH,PHONE,POSTNUM,ADDRESS,DETADD,LVL,UPOINT,INUM,REGDT) values ('j07_145','7777','이상무145_07','1977/07/07','010-7777-7777',77777,'주소7','상세주소7',0,1000,7777,to_date('19/09/30','RR/MM/DD'));
Insert into REDBULL.RUSER (RID,PASSWD,UNAME,BIRTH,PHONE,POSTNUM,ADDRESS,DETADD,LVL,UPOINT,INUM,REGDT) values ('j08_145','7777','이상무145_07','1977/07/07','010-7777-7777',77777,'주소7','상세주소7',0,0,7777,to_date('19/09/30','RR/MM/DD'));
Insert into REDBULL.RUSER (RID,PASSWD,UNAME,BIRTH,PHONE,POSTNUM,ADDRESS,DETADD,LVL,UPOINT,INUM,REGDT) values ('j03_145','password','이상무145_03','1900/01/01','010-1111-1111',12345,'주소','상세주소',30,0,9999,to_date('19/10/01','RR/MM/DD'));
Insert into REDBULL.RUSER (RID,PASSWD,UNAME,BIRTH,PHONE,POSTNUM,ADDRESS,DETADD,LVL,UPOINT,INUM,REGDT) values ('sytemp1234@naver.com','password','이상무145_02','1900/01/01','010-1111-1111',12345,'주소','상세주소',30,3000,9999,to_date('19/10/02','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index PK_BOARD
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_BOARD" ON "REDBULL"."BOARD" ("BNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_CART
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_CART" ON "REDBULL"."CART" ("CARTNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_CODE" ON "REDBULL"."CODE" ("CODE_TYPE_ID", "CODE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_CODE_TYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_CODE_TYPE" ON "REDBULL"."CODE_TYPE" ("CODE_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_COM
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_COM" ON "REDBULL"."COMMENTS" ("CNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_GOOD
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_GOOD" ON "REDBULL"."GOOD" ("GNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_IMAGE
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_IMAGE" ON "REDBULL"."IMAGE" ("INUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_OPT
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_OPT" ON "REDBULL"."OPT" ("ONUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_PAY
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_PAY" ON "REDBULL"."PAY" ("PAYNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_PRODUCT
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_PRODUCT" ON "REDBULL"."PRODUCT" ("PNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_REVIEW
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_REVIEW" ON "REDBULL"."REVIEW" ("RNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_RUSER
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_RUSER" ON "REDBULL"."RUSER" ("RID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "REDBULL"."BOARD" MODIFY ("BNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."BOARD" MODIFY ("CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."BOARD" MODIFY ("TNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."BOARD" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY ("BNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "REDBULL"."PRODUCT" MODIFY ("PNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PRODUCT" MODIFY ("PNAME" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PRODUCT" MODIFY ("BPRICE" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY ("PNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RUSER
--------------------------------------------------------

  ALTER TABLE "REDBULL"."RUSER" MODIFY ("RID" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."RUSER" MODIFY ("PASSWD" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."RUSER" MODIFY ("UNAME" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."RUSER" MODIFY ("BIRTH" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."RUSER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."RUSER" MODIFY ("POSTNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."RUSER" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."RUSER" ADD CONSTRAINT "PK_RUSER" PRIMARY KEY ("RID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CODE
--------------------------------------------------------

  ALTER TABLE "REDBULL"."CODE" MODIFY ("CODE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."CODE" MODIFY ("CODE_ID" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."CODE" MODIFY ("CODE_NM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."CODE" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."CODE" ADD CONSTRAINT "PK_CODE" PRIMARY KEY ("CODE_TYPE_ID", "CODE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "REDBULL_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GOOD
--------------------------------------------------------

  ALTER TABLE "REDBULL"."GOOD" MODIFY ("GNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."GOOD" MODIFY ("PNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."GOOD" ADD CONSTRAINT "PK_GOOD" PRIMARY KEY ("GNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CODE_TYPE
--------------------------------------------------------

  ALTER TABLE "REDBULL"."CODE_TYPE" MODIFY ("CODE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."CODE_TYPE" MODIFY ("CODE_TYPE_NM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."CODE_TYPE" ADD CONSTRAINT "PK_CODE_TYPE" PRIMARY KEY ("CODE_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "REDBULL_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OPT
--------------------------------------------------------

  ALTER TABLE "REDBULL"."OPT" MODIFY ("ONUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."OPT" MODIFY ("ONAME" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."OPT" MODIFY ("OPRICE" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."OPT" MODIFY ("PNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."OPT" ADD CONSTRAINT "PK_OPT" PRIMARY KEY ("ONUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS"  ENABLE;
  ALTER TABLE "REDBULL"."OPT" MODIFY ("INUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAY
--------------------------------------------------------

  ALTER TABLE "REDBULL"."PAY" MODIFY ("PAYNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PAY" MODIFY ("ORDERNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PAY" MODIFY ("ONUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PAY" MODIFY ("PAYCNT" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PAY" MODIFY ("DNAME" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PAY" MODIFY ("DPOSTNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PAY" MODIFY ("DAAD" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PAY" MODIFY ("DPHONE" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PAY" MODIFY ("PAYID" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PAY" ADD CONSTRAINT "PK_PAY" PRIMARY KEY ("PAYNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "REDBULL_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "REDBULL"."REVIEW" MODIFY ("RNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."REVIEW" MODIFY ("PNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."REVIEW" MODIFY ("SCORE" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."REVIEW" MODIFY ("CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY ("RNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "REDBULL"."CART" MODIFY ("CARTNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."CART" MODIFY ("PNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."CART" MODIFY ("CARTCNT" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."CART" MODIFY ("REGID" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."CART" ADD CONSTRAINT "PK_CART" PRIMARY KEY ("CARTNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "REDBULL"."COMMENTS" MODIFY ("CNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."COMMENTS" MODIFY ("TNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."COMMENTS" MODIFY ("REFNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."COMMENTS" MODIFY ("CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."COMMENTS" ADD CONSTRAINT "PK_COM" PRIMARY KEY ("CNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IMAGE
--------------------------------------------------------

  ALTER TABLE "REDBULL"."IMAGE" MODIFY ("INUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."IMAGE" MODIFY ("ORG_FILE_NM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."IMAGE" MODIFY ("SAVE_FILE_NM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."IMAGE" MODIFY ("EXT_NM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."IMAGE" ADD CONSTRAINT "PK_IMAGE" PRIMARY KEY ("INUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS"  ENABLE;
