--------------------------------------------------------
--  파일이 생성됨 - 월요일-10월-21-2019   
--------------------------------------------------------
DROP TABLE "REDBULL"."BOARD" cascade constraints;
DROP TABLE "REDBULL"."CART" cascade constraints;
DROP TABLE "REDBULL"."CODE" cascade constraints;
DROP TABLE "REDBULL"."CODE_TYPE" cascade constraints;
DROP TABLE "REDBULL"."COMMENTS" cascade constraints;
DROP TABLE "REDBULL"."GOOD" cascade constraints;
DROP TABLE "REDBULL"."IMAGE" cascade constraints;
DROP TABLE "REDBULL"."OPT" cascade constraints;
DROP TABLE "REDBULL"."PAY" cascade constraints;
DROP TABLE "REDBULL"."PRODUCT" cascade constraints;
DROP TABLE "REDBULL"."REVIEW" cascade constraints;
DROP TABLE "REDBULL"."RUSER" cascade constraints;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "REDBULL"."BOARD" 
   (	"BNUM" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TITLE" VARCHAR2(100 CHAR), 
	"CONTENTS" CLOB, 
	"READCNT" NUMBER(7,0) DEFAULT 0, 
	"TNUM" NUMBER(3,0), 
	"CATEGORY" VARCHAR2(10 CHAR), 
	"REGID" VARCHAR2(320 CHAR), 
	"REGDT" DATE, 
	"MODID" VARCHAR2(320 CHAR), 
	"MODDT" DATE, 
	"FILE_ID" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" 
 LOB ("CONTENTS") STORE AS SECUREFILE (
  TABLESPACE "REDBULL_TS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "REDBULL"."BOARD"."BNUM" IS '질문번호';
   COMMENT ON COLUMN "REDBULL"."BOARD"."TITLE" IS '제목';
   COMMENT ON COLUMN "REDBULL"."BOARD"."CONTENTS" IS '내용';
   COMMENT ON COLUMN "REDBULL"."BOARD"."READCNT" IS '조회수';
   COMMENT ON COLUMN "REDBULL"."BOARD"."TNUM" IS '테이블번호';
   COMMENT ON COLUMN "REDBULL"."BOARD"."CATEGORY" IS '카테고리';
   COMMENT ON COLUMN "REDBULL"."BOARD"."REGID" IS '등록자';
   COMMENT ON COLUMN "REDBULL"."BOARD"."REGDT" IS '등록일';
   COMMENT ON COLUMN "REDBULL"."BOARD"."MODID" IS '수정자';
   COMMENT ON COLUMN "REDBULL"."BOARD"."MODDT" IS '수정일';
   COMMENT ON TABLE "REDBULL"."BOARD"  IS '게시판';
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "REDBULL"."CART" 
   (	"CARTNUM" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ONUM" NUMBER, 
	"CARTCNT" NUMBER(4,0) DEFAULT 1, 
	"REGID" VARCHAR2(320 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;

   COMMENT ON COLUMN "REDBULL"."CART"."CARTNUM" IS '장바구니번호';
   COMMENT ON COLUMN "REDBULL"."CART"."ONUM" IS '옵션번호';
   COMMENT ON COLUMN "REDBULL"."CART"."CARTCNT" IS '수량';
   COMMENT ON COLUMN "REDBULL"."CART"."REGID" IS '등록자';
   COMMENT ON TABLE "REDBULL"."CART"  IS '장바구니';
--------------------------------------------------------
--  DDL for Table CODE
--------------------------------------------------------

  CREATE TABLE "REDBULL"."CODE" 
   (	"CODE_TYPE_ID" VARCHAR2(30 BYTE), 
	"CODE_ID" VARCHAR2(30 BYTE), 
	"CODE_NM" VARCHAR2(100 BYTE), 
	"USE_YN" CHAR(1 BYTE) DEFAULT 0, 
	"NUM" NUMBER, 
	"REG_ID" VARCHAR2(20 BYTE), 
	"REG_DT" DATE, 
	"MOD_ID" VARCHAR2(20 BYTE), 
	"MOD_DT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "REDBULL_TS" ;

   COMMENT ON COLUMN "REDBULL"."CODE"."CODE_TYPE_ID" IS '코드유형ID';
   COMMENT ON COLUMN "REDBULL"."CODE"."CODE_ID" IS '코드ID';
   COMMENT ON COLUMN "REDBULL"."CODE"."CODE_NM" IS '코드명';
   COMMENT ON COLUMN "REDBULL"."CODE"."USE_YN" IS '사용여부';
   COMMENT ON COLUMN "REDBULL"."CODE"."NUM" IS '순서';
   COMMENT ON COLUMN "REDBULL"."CODE"."REG_ID" IS '등록자ID';
   COMMENT ON COLUMN "REDBULL"."CODE"."REG_DT" IS '등록일';
   COMMENT ON COLUMN "REDBULL"."CODE"."MOD_ID" IS '수정자ID';
   COMMENT ON COLUMN "REDBULL"."CODE"."MOD_DT" IS '수정일';
   COMMENT ON TABLE "REDBULL"."CODE"  IS '공통코드';
--------------------------------------------------------
--  DDL for Table CODE_TYPE
--------------------------------------------------------

  CREATE TABLE "REDBULL"."CODE_TYPE" 
   (	"CODE_TYPE_ID" VARCHAR2(30 BYTE), 
	"CODE_TYPE_NM" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "REDBULL_TS" ;

   COMMENT ON COLUMN "REDBULL"."CODE_TYPE"."CODE_TYPE_ID" IS '코드유형ID';
   COMMENT ON COLUMN "REDBULL"."CODE_TYPE"."CODE_TYPE_NM" IS '코드유형명';
   COMMENT ON TABLE "REDBULL"."CODE_TYPE"  IS '공통코드유형';
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "REDBULL"."COMMENTS" 
   (	"CNUM" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TNUM" NUMBER(3,0), 
	"REFNUM" NUMBER, 
	"CONTENTS" CLOB, 
	"HCNUM" NUMBER DEFAULT 0, 
	"REGID" VARCHAR2(320 CHAR), 
	"REGDT" DATE, 
	"MODID" VARCHAR2(320 CHAR), 
	"MODDT" DATE, 
	"CLEVEL" NUMBER(2,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" 
 LOB ("CONTENTS") STORE AS SECUREFILE (
  TABLESPACE "REDBULL_TS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "REDBULL"."COMMENTS"."CNUM" IS '댓글번호';
   COMMENT ON COLUMN "REDBULL"."COMMENTS"."TNUM" IS '테이블번호';
   COMMENT ON COLUMN "REDBULL"."COMMENTS"."REFNUM" IS '참조번호';
   COMMENT ON COLUMN "REDBULL"."COMMENTS"."CONTENTS" IS '내용';
   COMMENT ON COLUMN "REDBULL"."COMMENTS"."HCNUM" IS '상위댓글번호';
   COMMENT ON COLUMN "REDBULL"."COMMENTS"."REGID" IS '등록자';
   COMMENT ON COLUMN "REDBULL"."COMMENTS"."REGDT" IS '등록일';
   COMMENT ON COLUMN "REDBULL"."COMMENTS"."MODID" IS '수정자';
   COMMENT ON COLUMN "REDBULL"."COMMENTS"."MODDT" IS '수정일';
   COMMENT ON TABLE "REDBULL"."COMMENTS"  IS '댓글';
--------------------------------------------------------
--  DDL for Table GOOD
--------------------------------------------------------

  CREATE TABLE "REDBULL"."GOOD" 
   (	"GNUM" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PNUM" NUMBER, 
	"REGID" VARCHAR2(320 CHAR), 
	"REGDT" DATE, 
	"LINK" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;

   COMMENT ON COLUMN "REDBULL"."GOOD"."GNUM" IS '좋아요번호';
   COMMENT ON COLUMN "REDBULL"."GOOD"."PNUM" IS '상품번호';
   COMMENT ON COLUMN "REDBULL"."GOOD"."REGID" IS '등록자';
   COMMENT ON COLUMN "REDBULL"."GOOD"."REGDT" IS '등록일';
   COMMENT ON COLUMN "REDBULL"."GOOD"."LINK" IS '링크';
   COMMENT ON TABLE "REDBULL"."GOOD"  IS '좋아요';
--------------------------------------------------------
--  DDL for Table IMAGE
--------------------------------------------------------

  CREATE TABLE "REDBULL"."IMAGE" 
   (	"INUM" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"REFNUM" NUMBER, 
	"ORG_FILE_NM" VARCHAR2(255 CHAR), 
	"SAVE_FILE_NM" VARCHAR2(255 CHAR), 
	"FILE_SIZE" VARCHAR2(7 BYTE), 
	"EXT_NM" VARCHAR2(4 CHAR), 
	"FILE_ID" VARCHAR2(40 BYTE), 
	"NUM" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;

   COMMENT ON COLUMN "REDBULL"."IMAGE"."INUM" IS '이미지번호';
   COMMENT ON COLUMN "REDBULL"."IMAGE"."REFNUM" IS '참조번호';
   COMMENT ON COLUMN "REDBULL"."IMAGE"."ORG_FILE_NM" IS '원본파일명';
   COMMENT ON COLUMN "REDBULL"."IMAGE"."SAVE_FILE_NM" IS '저장파일명';
   COMMENT ON COLUMN "REDBULL"."IMAGE"."FILE_SIZE" IS '사이즈';
   COMMENT ON COLUMN "REDBULL"."IMAGE"."EXT_NM" IS '확장자';
   COMMENT ON TABLE "REDBULL"."IMAGE"  IS '이미지';
--------------------------------------------------------
--  DDL for Table OPT
--------------------------------------------------------

  CREATE TABLE "REDBULL"."OPT" 
   (	"ONUM" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ONAME" VARCHAR2(100 CHAR), 
	"OPRICE" NUMBER(7,0), 
	"PNUM" NUMBER, 
	"INUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;

   COMMENT ON COLUMN "REDBULL"."OPT"."ONUM" IS '옵션번호';
   COMMENT ON COLUMN "REDBULL"."OPT"."ONAME" IS '옵션명';
   COMMENT ON COLUMN "REDBULL"."OPT"."OPRICE" IS '가격';
   COMMENT ON COLUMN "REDBULL"."OPT"."PNUM" IS '상품번호';
   COMMENT ON COLUMN "REDBULL"."OPT"."INUM" IS '이미지번호';
   COMMENT ON TABLE "REDBULL"."OPT"  IS '옵션';
--------------------------------------------------------
--  DDL for Table PAY
--------------------------------------------------------

  CREATE TABLE "REDBULL"."PAY" 
   (	"PAYNUM" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ORDERNUM" NUMBER, 
	"ONUM" NUMBER, 
	"PAYCNT" NUMBER(4,0) DEFAULT 1, 
	"DNAME" VARCHAR2(17 CHAR), 
	"DPOSTNUM" NUMBER(5,0), 
	"DAAD" VARCHAR2(30 CHAR), 
	"DDETADD" VARCHAR2(100 CHAR), 
	"DPHONE" VARCHAR2(13 BYTE), 
	"DMEMO" VARCHAR2(100 CHAR), 
	"PAYID" VARCHAR2(320 CHAR), 
	"PAYDT" DATE, 
	"INUM" NUMBER, 
	"PAYMETHOD" VARCHAR2(30 BYTE) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "REDBULL_TS" ;

   COMMENT ON COLUMN "REDBULL"."PAY"."PAYNUM" IS '결제번호';
   COMMENT ON COLUMN "REDBULL"."PAY"."ORDERNUM" IS '주문번호';
   COMMENT ON COLUMN "REDBULL"."PAY"."ONUM" IS '옵션번호';
   COMMENT ON COLUMN "REDBULL"."PAY"."PAYCNT" IS '결제수량';
   COMMENT ON COLUMN "REDBULL"."PAY"."DNAME" IS '배송받는사람';
   COMMENT ON COLUMN "REDBULL"."PAY"."DPOSTNUM" IS '배송우편번호';
   COMMENT ON COLUMN "REDBULL"."PAY"."DAAD" IS '배송주소';
   COMMENT ON COLUMN "REDBULL"."PAY"."DDETADD" IS '배송자세한주소';
   COMMENT ON COLUMN "REDBULL"."PAY"."DPHONE" IS '배송휴대폰번호';
   COMMENT ON COLUMN "REDBULL"."PAY"."DMEMO" IS '배송메모';
   COMMENT ON COLUMN "REDBULL"."PAY"."PAYID" IS '결제자';
   COMMENT ON COLUMN "REDBULL"."PAY"."PAYDT" IS '결제일';
   COMMENT ON COLUMN "REDBULL"."PAY"."INUM" IS '이미지번호';
   COMMENT ON COLUMN "REDBULL"."PAY"."PAYMETHOD" IS '결제정보';
   COMMENT ON TABLE "REDBULL"."PAY"  IS '결제';
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "REDBULL"."PRODUCT" 
   (	"PNUM" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PNAME" VARCHAR2(100 CHAR), 
	"BPRICE" NUMBER(7,0), 
	"DETAIL" CLOB, 
	"DISCOUNT" NUMBER(3,2) DEFAULT 0, 
	"DPRICE" NUMBER(5,0) DEFAULT 0, 
	"PCATEGORY" NUMBER(3,0) DEFAULT 10, 
	"REGID" VARCHAR2(320 CHAR), 
	"REGDT" DATE, 
	"MODID" VARCHAR2(320 CHAR), 
	"MODDT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" 
 LOB ("DETAIL") STORE AS SECUREFILE (
  TABLESPACE "REDBULL_TS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "REDBULL"."PRODUCT"."PNUM" IS '상품번호';
   COMMENT ON COLUMN "REDBULL"."PRODUCT"."PNAME" IS '상품명';
   COMMENT ON COLUMN "REDBULL"."PRODUCT"."BPRICE" IS '기본가격';
   COMMENT ON COLUMN "REDBULL"."PRODUCT"."DETAIL" IS '상세정보';
   COMMENT ON COLUMN "REDBULL"."PRODUCT"."DISCOUNT" IS '할인율';
   COMMENT ON COLUMN "REDBULL"."PRODUCT"."DPRICE" IS '배송비';
   COMMENT ON COLUMN "REDBULL"."PRODUCT"."PCATEGORY" IS '카테고리';
   COMMENT ON COLUMN "REDBULL"."PRODUCT"."REGID" IS '등록자';
   COMMENT ON COLUMN "REDBULL"."PRODUCT"."REGDT" IS '등록일';
   COMMENT ON COLUMN "REDBULL"."PRODUCT"."MODID" IS '수정자';
   COMMENT ON COLUMN "REDBULL"."PRODUCT"."MODDT" IS '수정일';
   COMMENT ON TABLE "REDBULL"."PRODUCT"  IS '상품';
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE "REDBULL"."REVIEW" 
   (	"RNUM" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PNUM" NUMBER, 
	"SCORE" NUMBER(2,1) DEFAULT 0, 
	"CONTENTS" CLOB, 
	"REGID" VARCHAR2(320 CHAR), 
	"REGDT" DATE, 
	"MODID" VARCHAR2(320 CHAR), 
	"MODDT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" 
 LOB ("CONTENTS") STORE AS SECUREFILE (
  TABLESPACE "REDBULL_TS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "REDBULL"."REVIEW"."RNUM" IS '리뷰번호';
   COMMENT ON COLUMN "REDBULL"."REVIEW"."PNUM" IS '상품번호';
   COMMENT ON COLUMN "REDBULL"."REVIEW"."SCORE" IS '별점';
   COMMENT ON COLUMN "REDBULL"."REVIEW"."CONTENTS" IS '내용';
   COMMENT ON COLUMN "REDBULL"."REVIEW"."REGID" IS '등록자';
   COMMENT ON COLUMN "REDBULL"."REVIEW"."REGDT" IS '등록일';
   COMMENT ON COLUMN "REDBULL"."REVIEW"."MODID" IS '수정자';
   COMMENT ON COLUMN "REDBULL"."REVIEW"."MODDT" IS '수정일';
   COMMENT ON TABLE "REDBULL"."REVIEW"  IS '리뷰';
--------------------------------------------------------
--  DDL for Table RUSER
--------------------------------------------------------

  CREATE TABLE "REDBULL"."RUSER" 
   (	"RID" VARCHAR2(320 CHAR), 
	"PASSWD" VARCHAR2(20 BYTE), 
	"UNAME" VARCHAR2(17 CHAR), 
	"BIRTH" VARCHAR2(10 BYTE), 
	"PHONE" VARCHAR2(13 BYTE), 
	"POSTNUM" NUMBER(5,0), 
	"ADDRESS" VARCHAR2(100 CHAR), 
	"DETADD" VARCHAR2(100 CHAR), 
	"LVL" NUMBER(3,0) DEFAULT 10, 
	"UPOINT" NUMBER(6,0) DEFAULT 0, 
	"INUM" NUMBER, 
	"REGDT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;

   COMMENT ON COLUMN "REDBULL"."RUSER"."RID" IS '아이디';
   COMMENT ON COLUMN "REDBULL"."RUSER"."PASSWD" IS '비밀번호';
   COMMENT ON COLUMN "REDBULL"."RUSER"."UNAME" IS '이름';
   COMMENT ON COLUMN "REDBULL"."RUSER"."BIRTH" IS '생년월일';
   COMMENT ON COLUMN "REDBULL"."RUSER"."PHONE" IS '휴대폰번호';
   COMMENT ON COLUMN "REDBULL"."RUSER"."POSTNUM" IS '우편번호';
   COMMENT ON COLUMN "REDBULL"."RUSER"."ADDRESS" IS '주소';
   COMMENT ON COLUMN "REDBULL"."RUSER"."DETADD" IS '자세한주소';
   COMMENT ON COLUMN "REDBULL"."RUSER"."LVL" IS '레벨';
   COMMENT ON COLUMN "REDBULL"."RUSER"."UPOINT" IS '포인트';
   COMMENT ON COLUMN "REDBULL"."RUSER"."INUM" IS '이미지번호';
   COMMENT ON COLUMN "REDBULL"."RUSER"."REGDT" IS '등록일';
   COMMENT ON TABLE "REDBULL"."RUSER"  IS '회원';
REM INSERTING into REDBULL.BOARD
SET DEFINE OFF;
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT,FILE_ID) values (312,'ㅇㅀㅇㅀㅇㄹ',11,10,'공지',null,to_date('19/10/17','RR/MM/DD'),null,to_date('19/10/17','RR/MM/DD'),null);
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT,FILE_ID) values (262,'우왕',10,20,'질답카테고리03',null,to_date('19/09/30','RR/MM/DD'),null,to_date('19/09/30','RR/MM/DD'),null);
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT,FILE_ID) values (265,'1111111',25,10,'공지',null,to_date('19/09/30','RR/MM/DD'),null,to_date('19/09/30','RR/MM/DD'),null);
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT,FILE_ID) values (234,'test',1,10,'1',null,to_date('19/09/26','RR/MM/DD'),null,to_date('19/09/26','RR/MM/DD'),null);
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT,FILE_ID) values (235,'12312312312312313',2,10,'공지',null,to_date('19/09/26','RR/MM/DD'),null,to_date('19/09/26','RR/MM/DD'),null);
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT,FILE_ID) values (238,'공지테스트',3,10,'공지',null,to_date('19/09/26','RR/MM/DD'),null,to_date('19/09/26','RR/MM/DD'),null);
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT,FILE_ID) values (244,'테스트글쓰기',2,20,'질답카테고리02',null,to_date('19/09/27','RR/MM/DD'),null,to_date('19/09/27','RR/MM/DD'),null);
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT,FILE_ID) values (243,'수정',1,20,'질답카테고리01',null,to_date('19/09/27','RR/MM/DD'),null,to_date('19/09/27','RR/MM/DD'),null);
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT,FILE_ID) values (245,'공지테스트',6,10,'공지',null,to_date('19/09/27','RR/MM/DD'),null,to_date('19/09/27','RR/MM/DD'),null);
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT,FILE_ID) values (246,'공지1',2,10,'공지',null,to_date('19/09/27','RR/MM/DD'),null,to_date('19/09/27','RR/MM/DD'),null);
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT,FILE_ID) values (247,'공지공지공지',16,10,'공지',null,to_date('19/09/27','RR/MM/DD'),null,to_date('19/09/27','RR/MM/DD'),null);
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT,FILE_ID) values (248,'111111',0,20,'질답카테고리03',null,to_date('19/09/27','RR/MM/DD'),null,to_date('19/09/27','RR/MM/DD'),null);
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT,FILE_ID) values (249,'123131231',3,20,'질답카테고리04',null,to_date('19/09/27','RR/MM/DD'),null,to_date('19/09/27','RR/MM/DD'),null);
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT,FILE_ID) values (250,'123121111111',5,20,'질답카테고리04',null,to_date('19/09/27','RR/MM/DD'),null,to_date('19/09/27','RR/MM/DD'),null);
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT,FILE_ID) values (264,'좁은 집 벽지 무슨 색이 좋을까요',1083,20,'질답카테고리02',null,to_date('19/09/30','RR/MM/DD'),null,to_date('19/10/18','RR/MM/DD'),null);
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT,FILE_ID) values (204,'update',5,10,'update','admin',to_date('19/09/25','RR/MM/DD'),'update',to_date('19/09/25','RR/MM/DD'),null);
Insert into REDBULL.BOARD (BNUM,TITLE,READCNT,TNUM,CATEGORY,REGID,REGDT,MODID,MODDT,FILE_ID) values (332,'인테리어 질문',47,20,'질답카테고리01',null,to_date('19/10/18','RR/MM/DD'),null,to_date('19/10/18','RR/MM/DD'),null);
REM INSERTING into REDBULL.CART
SET DEFINE OFF;
Insert into REDBULL.CART (CARTNUM,ONUM,CARTCNT,REGID) values (249,83,3,'fnnjdd@naver.com');
Insert into REDBULL.CART (CARTNUM,ONUM,CARTCNT,REGID) values (258,63,1,'fnnjdd@naver.com');
REM INSERTING into REDBULL.CODE
SET DEFINE OFF;
REM INSERTING into REDBULL.CODE_TYPE
SET DEFINE OFF;
REM INSERTING into REDBULL.COMMENTS
SET DEFINE OFF;
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (159,20,264,0,'admin',to_date('19/10/02','RR/MM/DD'),null,to_date('19/10/16','RR/MM/DD'),1);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (160,20,264,0,'admin',to_date('19/10/02','RR/MM/DD'),'test',to_date('19/10/16','RR/MM/DD'),1);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (161,20,264,159,'admin',to_date('19/10/02','RR/MM/DD'),null,to_date('19/10/16','RR/MM/DD'),2);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (162,20,264,160,'admin',to_date('19/10/02','RR/MM/DD'),'test',to_date('19/10/16','RR/MM/DD'),2);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (163,20,264,162,'admin',to_date('19/10/02','RR/MM/DD'),'test',to_date('19/10/16','RR/MM/DD'),3);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (211,20,262,0,'test',to_date('19/10/16','RR/MM/DD'),null,to_date('19/10/16','RR/MM/DD'),1);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (212,20,262,211,'test',to_date('19/10/16','RR/MM/DD'),null,to_date('19/10/16','RR/MM/DD'),2);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (201,20,264,0,'test',to_date('19/10/15','RR/MM/DD'),'test',to_date('19/10/16','RR/MM/DD'),1);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (215,20,264,0,'test',to_date('19/10/16','RR/MM/DD'),'test',to_date('19/10/16','RR/MM/DD'),1);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (200,20,264,0,'test',to_date('19/10/15','RR/MM/DD'),'test',to_date('19/10/16','RR/MM/DD'),1);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (202,20,264,159,'test',to_date('19/10/15','RR/MM/DD'),'test',to_date('19/10/18','RR/MM/DD'),2);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (203,20,264,0,'test',to_date('19/10/15','RR/MM/DD'),'test',to_date('19/10/16','RR/MM/DD'),1);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (185,20,264,163,'test',to_date('19/10/15','RR/MM/DD'),'test',to_date('19/10/16','RR/MM/DD'),4);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (218,10,265,217,'test',to_date('19/10/16','RR/MM/DD'),null,to_date('19/10/16','RR/MM/DD'),2);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (206,20,264,0,'test',to_date('19/10/16','RR/MM/DD'),'test',to_date('19/10/16','RR/MM/DD'),1);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (221,20,264,192,'test',to_date('19/10/17','RR/MM/DD'),null,to_date('19/10/17','RR/MM/DD'),4);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (207,20,264,159,'test',to_date('19/10/16','RR/MM/DD'),'test',to_date('19/10/16','RR/MM/DD'),2);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (208,20,264,207,'test',to_date('19/10/16','RR/MM/DD'),'test',to_date('19/10/16','RR/MM/DD'),3);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (191,20,264,159,'test',to_date('19/10/15','RR/MM/DD'),null,to_date('19/10/18','RR/MM/DD'),2);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (192,20,264,191,'test',to_date('19/10/15','RR/MM/DD'),'test',to_date('19/10/16','RR/MM/DD'),3);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (209,20,264,202,'test',to_date('19/10/16','RR/MM/DD'),'test',to_date('19/10/16','RR/MM/DD'),3);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (210,20,264,0,'test',to_date('19/10/16','RR/MM/DD'),'test',to_date('19/10/16','RR/MM/DD'),1);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (217,10,265,0,'test',to_date('19/10/16','RR/MM/DD'),null,to_date('19/10/16','RR/MM/DD'),1);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (196,20,264,159,'test',to_date('19/10/15','RR/MM/DD'),'test',to_date('19/10/18','RR/MM/DD'),2);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (241,10,245,0,'test',to_date('19/10/18','RR/MM/DD'),null,to_date('19/10/18','RR/MM/DD'),1);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (242,10,245,241,'test',to_date('19/10/18','RR/MM/DD'),null,to_date('19/10/18','RR/MM/DD'),2);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (244,20,332,0,'test',to_date('19/10/18','RR/MM/DD'),null,to_date('19/10/18','RR/MM/DD'),1);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (216,20,264,0,'test',to_date('19/10/16','RR/MM/DD'),null,to_date('19/10/16','RR/MM/DD'),1);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (199,20,264,0,'test',to_date('19/10/15','RR/MM/DD'),null,to_date('19/10/18','RR/MM/DD'),1);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (198,20,264,0,'test',to_date('19/10/15','RR/MM/DD'),'test',to_date('19/10/16','RR/MM/DD'),1);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (205,20,242,0,'test',null,null,null,1);
Insert into REDBULL.COMMENTS (CNUM,TNUM,REFNUM,HCNUM,REGID,REGDT,MODID,MODDT,CLEVEL) values (243,20,329,0,'test',to_date('19/10/18','RR/MM/DD'),null,to_date('19/10/18','RR/MM/DD'),1);
REM INSERTING into REDBULL.GOOD
SET DEFINE OFF;
Insert into REDBULL.GOOD (GNUM,PNUM,REGID,REGDT,LINK) values (172,140,'J06등록자_135',to_date('19/10/14','RR/MM/DD'),'J06링크_135');
Insert into REDBULL.GOOD (GNUM,PNUM,REGID,REGDT,LINK) values (173,141,'J07등록자_135',to_date('19/10/14','RR/MM/DD'),'J07링크_135');
Insert into REDBULL.GOOD (GNUM,PNUM,REGID,REGDT,LINK) values (174,142,'J08등록자_135',to_date('19/10/14','RR/MM/DD'),'J08링크_135');
Insert into REDBULL.GOOD (GNUM,PNUM,REGID,REGDT,LINK) values (175,143,'J09등록자_135',to_date('19/10/14','RR/MM/DD'),'J09링크_135');
Insert into REDBULL.GOOD (GNUM,PNUM,REGID,REGDT,LINK) values (176,144,'J10등록자_135',to_date('19/10/14','RR/MM/DD'),'J10링크_135');
REM INSERTING into REDBULL.IMAGE
SET DEFINE OFF;
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (141,401,'product-2.PNG','resources\img\product\2019\10\product-2.PNG','1671563','PNG',null,null);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (142,401,'product-1.PNG','resources\img\product\2019\10\product-1.PNG','1457287','PNG',null,null);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (273,null,'board_seq.PNG','resources\img\board\2019\10\board_seq.PNG','3289','PNG','20191018ecd49b03e1c8442a824ee7c2275713e8',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (274,null,'board.PNG','resources\img\board\2019\10\board4.PNG','12726','PNG','2019101845188cfc06ce43229e41b1dc7c8225eb',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (275,null,'board.PNG','resources\img\board\2019\10\board5.PNG','12726','PNG','2019101849c0c19a558d4a8f85eab3c502f03202',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (276,null,'board.PNG','resources\img\board\2019\10\board6.PNG','12726','PNG','201910181d3b35c9ba894651a3f8117281175a65',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (271,null,'board.PNG','resources\img\board\2019\10\board2.PNG','12726','PNG','201910180732f8a2feb84a6fb9c9db16ccd5c53c',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (272,null,'board.PNG','resources\img\board\2019\10\board3.PNG','12726','PNG','20191018edc886ef18074c36983ba7a4c07cd9f3',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (86,396,'product_img1.PNG','resources\img\product\2019\10\product_img12.PNG','555343','PNG',null,null);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (87,396,'product_img2.PNG','resources\img\product\2019\10\product_img22.PNG','235268','PNG',null,null);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (88,396,'product_img3.PNG','resources\img\product\2019\10\product_img32.PNG','253364','PNG',null,null);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (301,null,'noimage.jpg','img\board\2019\10\noimage.jpg','3099','jpg','2019101825948d8458264b16b293313758ee896a',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (268,null,'comment.png','resources\img\board\2019\10\comment.png','1434','png','20191018443775e2aa384ffd97b272872cd337f3',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (269,null,'board.PNG','resources\img\board\2019\10\board.PNG','12726','PNG','20191018a0892734bb124dacbde89dccffb4ff90',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (103,402,'product-1.PNG','resources\img\product\2019\10\product-11.PNG','907676','PNG',null,null);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (104,402,'product-2.PNG','resources\img\product\2019\10\product-21.PNG','886052','PNG',null,null);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (122,422,'product.PNG','resources\img\product\2019\10\product3.PNG','1029999','PNG',null,null);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (270,null,'board.PNG','resources\img\board\2019\10\board1.PNG','12726','PNG','20191018daeb01cbe2ce41cc8dbbcae5b1ca56d8',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (278,null,'board.PNG','img\board\2019\10\board8.PNG','12726','PNG','20191018742a933d51a044f7907c81a6da386ba5',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (279,null,'board.PNG','img\board\2019\10\board9.PNG','12726','PNG','20191018238c31b411854a4f991eb42becec59c0',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (280,null,'board.PNG','img\board\2019\10\board10.PNG','12726','PNG','20191018a831bc5199264c8d9a83195086a406f7',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (281,null,'board.PNG','img\board\2019\10\board11.PNG','12726','PNG','2019101810b71b2d49104eeab69b81a219aef8a6',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (282,null,'board.PNG','img\board\2019\10\board12.PNG','12726','PNG','20191018c7bff7998d414c398fbb238c7eada15c',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (283,null,'board.PNG','img\board\2019\10\board13.PNG','12726','PNG','201910187a9645ae7e2a492d9b8822025c65903a',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (284,null,'board_seq.PNG','img\board\2019\10\board_seq1.PNG','3289','PNG','20191018bdc354618e0a4b649322b50eeb5f59e8',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (285,null,'board.PNG','img\board\2019\10\board14.PNG','12726','PNG','20191018de513ac03f6a4ddda7bd75a95c585295',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (286,null,'board.PNG','img\board\2019\10\board15.PNG','12726','PNG','20191018f79b73c1ea1a4bd8b9d3d57653ed4cec',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (288,null,'noimage.jpg','img\board\2019\10\noimage.jpg','3099','jpg','20191018dae3d374fa784dc0b07afff9d8a09b24',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (289,null,'noimage.jpg','img\board\2019\10\noimage1.jpg','3099','jpg','20191018d8fe1ecbfc0b4503bf971dea7435f5e8',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (290,null,'noimage.jpg','img\board\2019\10\noimage2.jpg','3099','jpg','20191018c2c7ad3185bb4ce7855889c0704ffc01',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (291,null,'comment.png','img\board\2019\10\comment2.png','1434','png','2019101886c01b50e82b4fdd9da2d6d419a7fa73',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (292,null,'noimage.jpg','img\board\2019\10\noimage3.jpg','3099','jpg','2019101825fb7897994e4663a75a9e16206da88b',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (293,null,'noimage.jpg','img\board\2019\10\noimage.jpg','3099','jpg','201910183db30d0d7ed24a89a64e623850e392fd',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (294,null,'comment.png','img\board\2019\10\comment.png','1434','png','2019101803f1fb7ad421439abfea3acefe9d7106',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (295,null,'2019040502816_0.jpg','img\board\2019\10\2019040502816_0.jpg','51853','jpg','20191018c426b2f2aaf84883bbd56d657d99d2e3',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (296,null,'comment.png','img\board\2019\10\comment1.png','1434','png','2019101854a0602aa06e45788ec8219ece41adaa',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (297,null,'noimage.jpg','img\board\2019\10\noimage1.jpg','3099','jpg','20191018c78e560e29e840f9a994c2bd9aa7c0a3',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (298,null,'다운로드.png','img\board\2019\10\다운로드.png','3650','png','2019101872a9a76200bc48f89fee18acfbf8f1db',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (299,null,'noimage.jpg','img\board\2019\10\noimage2.jpg','3099','jpg','20191018fba77a90a8f74357b049735ae9522475',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (300,null,'comment.png','img\board\2019\10\comment2.png','1434','png','201910188125bf17fc8d494b8e475e02ca268e0e',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (302,null,'2019040502816_0.jpg','img\board\2019\10\2019040502816_0.jpg','51853','jpg','201910184fc026743c9c414c84a9b199a4724f4c',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (277,null,'board.PNG','resources\img\board\2019\10\board7.PNG','12726','PNG','201910180cb446ecb77441f99aadfab570cc2ab7',1);
Insert into REDBULL.IMAGE (INUM,REFNUM,ORG_FILE_NM,SAVE_FILE_NM,FILE_SIZE,EXT_NM,FILE_ID,NUM) values (287,null,'comment.png','img\board\2019\10\comment1.png','1434','png','20191018e7d4e8153c2a406cbcc5506ecf79336b',1);
REM INSERTING into REDBULL.OPT
SET DEFINE OFF;
Insert into REDBULL.OPT (ONUM,ONAME,OPRICE,PNUM,INUM) values (101,'컬러: 01. 세미극세사 레오 / 구성: SS이불단품',34400,401,null);
Insert into REDBULL.OPT (ONUM,ONAME,OPRICE,PNUM,INUM) values (102,'컬러: 02. 세미극세사 블랑부케 / 구성: Q이불단품',43900,401,null);
Insert into REDBULL.OPT (ONUM,ONAME,OPRICE,PNUM,INUM) values (47,'사이즈: 소(60x40x27) / 선택: 01_생각',12900,396,null);
Insert into REDBULL.OPT (ONUM,ONAME,OPRICE,PNUM,INUM) values (48,'사이즈: 중(72x48x27) / 선택: 02_깨달음',21900,396,null);
Insert into REDBULL.OPT (ONUM,ONAME,OPRICE,PNUM,INUM) values (49,'사이즈: 대(80x60x27) / 선택: 06_플라워',24900,396,null);
Insert into REDBULL.OPT (ONUM,ONAME,OPRICE,PNUM,INUM) values (63,'테이블선택: 루나테이블 / 사이즈선택: 1200사이즈',199000,402,null);
Insert into REDBULL.OPT (ONUM,ONAME,OPRICE,PNUM,INUM) values (64,'테이블선택: 릴리테이블 / 사이즈선택: 1800사이즈',359000,402,null);
Insert into REDBULL.OPT (ONUM,ONAME,OPRICE,PNUM,INUM) values (83,'[행사] 01.삼나무 미니싱글(XS) 600 원목 깔판',14400,422,null);
Insert into REDBULL.OPT (ONUM,ONAME,OPRICE,PNUM,INUM) values (84,'[행사] 02.삼나무 멀티싱글(MS) 750 원목 깔판',19400,422,null);
REM INSERTING into REDBULL.PAY
SET DEFINE OFF;
REM INSERTING into REDBULL.PRODUCT
SET DEFINE OFF;
Insert into REDBULL.PRODUCT (PNUM,PNAME,BPRICE,DISCOUNT,DPRICE,PCATEGORY,REGID,REGDT,MODID,MODDT) values (441,'무브 소프트 세미 극세사 차렵이불',34400,0.39,2500,20,null,to_date('19/10/16','RR/MM/DD'),null,null);
Insert into REDBULL.PRODUCT (PNUM,PNAME,BPRICE,DISCOUNT,DPRICE,PCATEGORY,REGID,REGDT,MODID,MODDT) values (396,'액자테이블 3종 택1',12900,0.5,0,30,null,to_date('19/10/08','RR/MM/DD'),null,null);
Insert into REDBULL.PRODUCT (PNUM,PNAME,BPRICE,DISCOUNT,DPRICE,PCATEGORY,REGID,REGDT,MODID,MODDT) values (402,'이태리 세라믹 식탁/식탁세트 4인',709000,0.71,60000,10,null,to_date('19/10/09','RR/MM/DD'),null,null);
Insert into REDBULL.PRODUCT (PNUM,PNAME,BPRICE,DISCOUNT,DPRICE,PCATEGORY,REGID,REGDT,MODID,MODDT) values (422,'북유럽 삼나무 원목 침대깔판',14400,0.77,15000,30,null,to_date('19/10/31','RR/MM/DD'),null,null);
REM INSERTING into REDBULL.REVIEW
SET DEFINE OFF;
Insert into REDBULL.REVIEW (RNUM,PNUM,SCORE,REGID,REGDT,MODID,MODDT) values (61,71,1,'noUser',to_date('19/10/02','RR/MM/DD'),null,null);
Insert into REDBULL.REVIEW (RNUM,PNUM,SCORE,REGID,REGDT,MODID,MODDT) values (62,72,2,'noUser',to_date('19/10/02','RR/MM/DD'),null,null);
Insert into REDBULL.REVIEW (RNUM,PNUM,SCORE,REGID,REGDT,MODID,MODDT) values (63,73,3,'noUser',to_date('19/10/02','RR/MM/DD'),null,null);
Insert into REDBULL.REVIEW (RNUM,PNUM,SCORE,REGID,REGDT,MODID,MODDT) values (64,74,4,'noUser',to_date('19/10/02','RR/MM/DD'),null,null);
Insert into REDBULL.REVIEW (RNUM,PNUM,SCORE,REGID,REGDT,MODID,MODDT) values (65,75,5,'noUser',to_date('19/10/02','RR/MM/DD'),null,null);
REM INSERTING into REDBULL.RUSER
SET DEFINE OFF;
Insert into REDBULL.RUSER (RID,PASSWD,UNAME,BIRTH,PHONE,POSTNUM,ADDRESS,DETADD,LVL,UPOINT,INUM,REGDT) values ('rid','passwd','uname','1900-01-01','010-1111-1111',12345,'address','detadd',10,0,0,to_date('19/09/27','RR/MM/DD'));
Insert into REDBULL.RUSER (RID,PASSWD,UNAME,BIRTH,PHONE,POSTNUM,ADDRESS,DETADD,LVL,UPOINT,INUM,REGDT) values ('j03_145','password','이상무145_03','1900/01/01','010-1111-1111',12345,'주소','상세주소',30,0,9999,to_date('19/10/07','RR/MM/DD'));
Insert into REDBULL.RUSER (RID,PASSWD,UNAME,BIRTH,PHONE,POSTNUM,ADDRESS,DETADD,LVL,UPOINT,INUM,REGDT) values ('j01_145','1234_u','업데이트','uuuu-uu-uu','uuu-uuuu-uuuu',1212,'업데이트','업데이트',30,1212,1212,to_date('19/10/18','RR/MM/DD'));
Insert into REDBULL.RUSER (RID,PASSWD,UNAME,BIRTH,PHONE,POSTNUM,ADDRESS,DETADD,LVL,UPOINT,INUM,REGDT) values ('sytemp1234@naver.com','aaaa','aaaa','aaaa','aaaa',54321,'aaaa','aaaa',10,10,0,to_date('19/10/21','RR/MM/DD'));
Insert into REDBULL.RUSER (RID,PASSWD,UNAME,BIRTH,PHONE,POSTNUM,ADDRESS,DETADD,LVL,UPOINT,INUM,REGDT) values ('jsptest','jsptest','jsptest','jsptest','jsptest',3993,'서울 마포구 동교로 217 (동교동)','11',10,0,0,to_date('19/10/08','RR/MM/DD'));
Insert into REDBULL.RUSER (RID,PASSWD,UNAME,BIRTH,PHONE,POSTNUM,ADDRESS,DETADD,LVL,UPOINT,INUM,REGDT) values ('test10','test10','uuuu','uuuu-uu-uu','uuu-uuuu-uuuu',12345,'uuuu','uuuu',10,0,0,to_date('19/10/21','RR/MM/DD'));
Insert into REDBULL.RUSER (RID,PASSWD,UNAME,BIRTH,PHONE,POSTNUM,ADDRESS,DETADD,LVL,UPOINT,INUM,REGDT) values ('jsptest1014','jsptest1014','jsptest1014','aaaa','aaaa',13524,'경기 성남시 분당구 대왕판교로606번길 45 (삼평동)','aaaa',10,0,0,to_date('19/10/14','RR/MM/DD'));
Insert into REDBULL.RUSER (RID,PASSWD,UNAME,BIRTH,PHONE,POSTNUM,ADDRESS,DETADD,LVL,UPOINT,INUM,REGDT) values ('j07_145','7777','이상무145_07','1977/07/07','010-7777-7777',77777,'주소7','상세주소7',20,1000,7777,to_date('19/09/30','RR/MM/DD'));
Insert into REDBULL.RUSER (RID,PASSWD,UNAME,BIRTH,PHONE,POSTNUM,ADDRESS,DETADD,LVL,UPOINT,INUM,REGDT) values ('ㅇㅇㅇ','3333','dd','1998-08-03','000-222-1111',6097,'서울 강남구 봉은사로 403 (삼성동)','ㅀ',10,0,0,to_date('19/10/21','RR/MM/DD'));
Insert into REDBULL.RUSER (RID,PASSWD,UNAME,BIRTH,PHONE,POSTNUM,ADDRESS,DETADD,LVL,UPOINT,INUM,REGDT) values ('test01','test01','test01','test01','test01',63534,'제주특별자치도 서귀포시 가가로 14 (상예동)',null,20,500,0,to_date('19/10/21','RR/MM/DD'));
Insert into REDBULL.RUSER (RID,PASSWD,UNAME,BIRTH,PHONE,POSTNUM,ADDRESS,DETADD,LVL,UPOINT,INUM,REGDT) values ('fnnjdd@naver.com','dms7014','dud','1995-05-03','010-9273-7014',13536,'경기 성남시 분당구 판교역로 4 (백현동)','102동',10,0,0,to_date('19/10/21','RR/MM/DD'));
Insert into REDBULL.RUSER (RID,PASSWD,UNAME,BIRTH,PHONE,POSTNUM,ADDRESS,DETADD,LVL,UPOINT,INUM,REGDT) values ('test02','test02','test02','test02','test02',13480,'경기 성남시 분당구 대왕판교로 477 (판교동)','test02',10,0,0,to_date('19/10/21','RR/MM/DD'));
Insert into REDBULL.RUSER (RID,PASSWD,UNAME,BIRTH,PHONE,POSTNUM,ADDRESS,DETADD,LVL,UPOINT,INUM,REGDT) values ('j08_145','7777','이상무145_07','1977/07/07','010-7777-7777',77777,'주소7','상세주소7',20,0,7777,to_date('19/09/30','RR/MM/DD'));
Insert into REDBULL.RUSER (RID,PASSWD,UNAME,BIRTH,PHONE,POSTNUM,ADDRESS,DETADD,LVL,UPOINT,INUM,REGDT) values ('admin','admin','관리자','admin','admin',134,'admin','admin',90,50000,0,to_date('19/10/14','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index PK_BOARD
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_BOARD" ON "REDBULL"."BOARD" ("BNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_CART
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_CART" ON "REDBULL"."CART" ("CARTNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_CODE" ON "REDBULL"."CODE" ("CODE_TYPE_ID", "CODE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_CODE_TYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_CODE_TYPE" ON "REDBULL"."CODE_TYPE" ("CODE_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_COM
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_COM" ON "REDBULL"."COMMENTS" ("CNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_GOOD
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_GOOD" ON "REDBULL"."GOOD" ("GNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_IMAGE
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_IMAGE" ON "REDBULL"."IMAGE" ("INUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_OPT
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_OPT" ON "REDBULL"."OPT" ("ONUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_PAY
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_PAY" ON "REDBULL"."PAY" ("PAYNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_PRODUCT
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_PRODUCT" ON "REDBULL"."PRODUCT" ("PNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_REVIEW
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_REVIEW" ON "REDBULL"."REVIEW" ("RNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  DDL for Index PK_RUSER
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDBULL"."PK_RUSER" ON "REDBULL"."RUSER" ("RID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "REDBULL"."BOARD" MODIFY ("BNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."BOARD" MODIFY ("CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."BOARD" MODIFY ("TNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."BOARD" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY ("BNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "REDBULL"."PRODUCT" MODIFY ("PNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PRODUCT" MODIFY ("PNAME" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PRODUCT" MODIFY ("BPRICE" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY ("PNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RUSER
--------------------------------------------------------

  ALTER TABLE "REDBULL"."RUSER" MODIFY ("RID" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."RUSER" MODIFY ("PASSWD" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."RUSER" MODIFY ("UNAME" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."RUSER" MODIFY ("BIRTH" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."RUSER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."RUSER" MODIFY ("POSTNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."RUSER" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."RUSER" ADD CONSTRAINT "PK_RUSER" PRIMARY KEY ("RID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CODE
--------------------------------------------------------

  ALTER TABLE "REDBULL"."CODE" MODIFY ("CODE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."CODE" MODIFY ("CODE_ID" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."CODE" MODIFY ("CODE_NM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."CODE" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."CODE" ADD CONSTRAINT "PK_CODE" PRIMARY KEY ("CODE_TYPE_ID", "CODE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "REDBULL_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GOOD
--------------------------------------------------------

  ALTER TABLE "REDBULL"."GOOD" MODIFY ("GNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."GOOD" MODIFY ("PNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."GOOD" ADD CONSTRAINT "PK_GOOD" PRIMARY KEY ("GNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CODE_TYPE
--------------------------------------------------------

  ALTER TABLE "REDBULL"."CODE_TYPE" MODIFY ("CODE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."CODE_TYPE" MODIFY ("CODE_TYPE_NM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."CODE_TYPE" ADD CONSTRAINT "PK_CODE_TYPE" PRIMARY KEY ("CODE_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "REDBULL_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OPT
--------------------------------------------------------

  ALTER TABLE "REDBULL"."OPT" MODIFY ("ONUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."OPT" MODIFY ("ONAME" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."OPT" MODIFY ("OPRICE" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."OPT" MODIFY ("PNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."OPT" ADD CONSTRAINT "PK_OPT" PRIMARY KEY ("ONUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAY
--------------------------------------------------------

  ALTER TABLE "REDBULL"."PAY" MODIFY ("PAYNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PAY" MODIFY ("ORDERNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PAY" MODIFY ("ONUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PAY" MODIFY ("PAYCNT" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PAY" MODIFY ("DNAME" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PAY" MODIFY ("DPOSTNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PAY" MODIFY ("DAAD" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PAY" MODIFY ("DPHONE" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PAY" MODIFY ("PAYID" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."PAY" ADD CONSTRAINT "PK_PAY" PRIMARY KEY ("PAYNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "REDBULL_TS"  ENABLE;
  ALTER TABLE "REDBULL"."PAY" MODIFY ("PAYMETHOD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "REDBULL"."REVIEW" MODIFY ("RNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."REVIEW" MODIFY ("PNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."REVIEW" MODIFY ("SCORE" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."REVIEW" MODIFY ("CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY ("RNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "REDBULL"."CART" MODIFY ("CARTNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."CART" MODIFY ("ONUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."CART" MODIFY ("CARTCNT" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."CART" MODIFY ("REGID" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."CART" ADD CONSTRAINT "PK_CART" PRIMARY KEY ("CARTNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "REDBULL"."COMMENTS" MODIFY ("CNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."COMMENTS" MODIFY ("TNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."COMMENTS" MODIFY ("REFNUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."COMMENTS" MODIFY ("CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."COMMENTS" ADD CONSTRAINT "PK_COM" PRIMARY KEY ("CNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IMAGE
--------------------------------------------------------

  ALTER TABLE "REDBULL"."IMAGE" MODIFY ("INUM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."IMAGE" MODIFY ("ORG_FILE_NM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."IMAGE" MODIFY ("SAVE_FILE_NM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."IMAGE" MODIFY ("EXT_NM" NOT NULL ENABLE);
  ALTER TABLE "REDBULL"."IMAGE" ADD CONSTRAINT "PK_IMAGE" PRIMARY KEY ("INUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REDBULL_TS"  ENABLE;
